ARG REPO_URL=https://github.com/Sean-Robinson-15/MovieWatchlist.git
ARG REF=main


FROM alpine/git AS source

ARG REPO_URL
ARG REF

WORKDIR /src

RUN git clone \
    --depth 1 \
    --branch "$REF" \
    "$REPO_URL" \
    .


FROM composer:2 AS dependencies

WORKDIR /app

COPY --from=source /src /app

RUN composer install \
    --no-dev \
    --prefer-dist \
    --no-interaction \
    --optimize-autoloader


FROM php:8.2-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends libsqlite3-dev \
    && docker-php-ext-install pdo_sqlite \
    && apt-get purge -y --auto-remove libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=dependencies /app /app

RUN mkdir -p /app/storage

EXPOSE 8000

CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]


